#!/usr/bin/env bash
#
# Bring the whole stack up on a fresh control-plane box.
#
# Written to be run once, on a new Lightsail instance, from a browser terminal
# where scp is not available and every file has to be created in place.
#
# It generates its own secrets rather than asking for them. The alternative is
# carrying the previous box's keys forward by hand through a paste buffer,
# which is both worse for secrecy and a good way to typo a 64-character hex
# string into a container that will not say why it failed. The only things it
# cannot generate are the Cloudflare tunnel credential, which identifies this
# tunnel to Cloudflare, and the optional third-party keys.
#
# Idempotent: an existing .env is never overwritten, so re-running it after a
# failure does not silently rotate the database password out from under a
# volume that still holds data encrypted with the old one.
set -euo pipefail

REPO_DIR="${REPO_DIR:-/opt/fleet-os}"
ZONE="${ZONE:-plastikworld.xyz}"
TUNNEL_ID="${TUNNEL_ID:-12b87f0b-6409-4ecb-9946-53bc1bef50a7}"
CRED="/etc/fleet-os/tunnel-credentials.json"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
die() { printf '\n\033[31mFATAL: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run with sudo"

say "1. the tunnel credential"
if [ ! -s "$CRED" ]; then
  cat <<EOF
  Missing: $CRED

  On your Mac, print it:
      cat ~/.cloudflared/${TUNNEL_ID}.json*

  Then here:
      sudo mkdir -p /etc/fleet-os
      sudo tee $CRED >/dev/null <<'JSON'
      <paste the single line of JSON>
      JSON

  Re-run this script afterwards.
EOF
  exit 1
fi
python3 -c "import json,sys; json.load(open('$CRED'))" 2>/dev/null \
  || die "$CRED is not valid JSON - a paste probably wrapped or lost a character"
chmod 600 "$CRED"
# cloudflared runs as uid 65532 inside its container and reads this file
# through a read-only mount. Owned by root at mode 600 it gets permission
# denied and the tunnel never connects - which is exactly how the last
# migration lost three minutes of production.
chown 65532:65532 "$CRED"
say "   credential present and owned by uid 65532"

say "2. the repository"
if [ ! -d "$REPO_DIR/.git" ]; then
  mkdir -p "$(dirname "$REPO_DIR")"
  git clone --depth 50 https://github.com/YadurajManu/fleet-os.git "$REPO_DIR"
else
  git -C "$REPO_DIR" pull --ff-only
fi
cd "$REPO_DIR"
say "   at $(git -C "$REPO_DIR" rev-parse --short HEAD)"

say "3. secrets and .env"
ENV_FILE="$REPO_DIR/deploy/.env"
if [ -s "$ENV_FILE" ]; then
  say "   .env already exists - keeping it (delete it to regenerate)"
else
  gen() { openssl rand -hex 32; }
  # SECRETS_MASTER_KEY is the one that is NOT hex. The control plane decodes it
  # as base64 and checks it lands on exactly 32 bytes, so a 64-character hex
  # string decodes to 48 and is rejected - with a clear message, but only after
  # a full build, and only in a container log.
  genb64() { openssl rand -base64 32; }
  REG_PASS=$(openssl rand -hex 16)
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/aws/bring-up.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# The database is created fresh with these values. Rotating POSTGRES_PASSWORD
# later without also resetting the volume leaves a database nothing can open.
POSTGRES_USER=fleetos
POSTGRES_DB=fleetos
POSTGRES_PASSWORD=$(gen)

JWT_SECRET=$(gen)
# Encrypts secrets at rest. Lose it and every stored secret is unreadable -
# there is no recovery path, by design.
SECRETS_MASTER_KEY=$(genb64)
WEBHOOK_SECRET=$(gen)

REGISTRY_URL=fleetregistry.$ZONE
REGISTRY_CREDENTIALS=fleet:$REG_PASS
REGISTRY_PORT=5001

INGRESS_ZONE=$ZONE
INGRESS_PORT=8081
API_PORT=8080
DASHBOARD_PORT=8082
WWW_PORT=8083

APP_URL=https://fleetapp.$ZONE
PUBLIC_DASHBOARD_URL=https://fleetapp.$ZONE
PUBLIC_API_URL=https://fleetapi.$ZONE

HEARTBEAT_INTERVAL_SEC=5
HEARTBEAT_MISS_THRESHOLD=3
LOG_LEVEL=info
BUILDX_CACHE_MODE=min

TUNNEL_CREDENTIALS=$CRED

# The gid of the host's docker group, so the control plane can use the socket
# it mounts. Wrong or missing, every build fails with "permission denied" and
# nothing else looks broken.
DOCKER_GID=$(getent group docker | cut -d: -f3)

# Optional. Email falls back to logging what it would have sent, so an
# unconfigured control plane still runs normally - it just goes quiet.
RESEND_API_KEY=
MAIL_FROM=
EOF
  chmod 600 "$ENV_FILE"
  say "   wrote $ENV_FILE with fresh secrets"
fi

say "4. tunnel ingress"
CF="$REPO_DIR/deploy/cloudflare/fleet-os.yml"
if [ ! -s "$CF" ]; then
  sed -e "s/REPLACE_WITH_TUNNEL_ID/$TUNNEL_ID/g" -e "s/REPLACE_ZONE/$ZONE/g" \
      "$REPO_DIR/deploy/cloudflare/fleet-os.yml.example" > "$CF"
  say "   rendered $CF"
fi
# This path is gitignored, so Docker will happily create a DIRECTORY here if
# the file is absent, mount it, and leave cloudflared reading an empty config
# with no error that names the cause. Refuse to continue on anything but a file.
[ -f "$CF" ] || die "$CF is not a regular file - remove it and re-run"

say "5. registry credentials"
# registry:2 has no access control of its own, so compose configures htpasswd
# auth and mounts deploy/registry-auth read-only. That directory is not in the
# repository, and a missing bind-mount source is not an error to Docker - it
# creates an empty directory, mounts it read-only, and the registry then panics
# with "failed to open htpasswd path ... read-only file system", which reads
# like a permissions bug rather than a missing file. Generate it from the
# credentials already in .env so the two cannot drift apart.
AUTH_DIR="$REPO_DIR/deploy/registry-auth"
if [ ! -s "$AUTH_DIR/htpasswd" ]; then
  CREDS=$(grep -E '^REGISTRY_CREDENTIALS=' "$ENV_FILE" | cut -d= -f2-)
  RU="${CREDS%%:*}"; RP="${CREDS#*:}"
  [ -n "$RU" ] && [ -n "$RP" ] && [ "$RU" != "$CREDS" ] \
    || die "REGISTRY_CREDENTIALS in $ENV_FILE must be user:password"
  mkdir -p "$AUTH_DIR"
  # bcrypt via the httpd image, so this needs no apache2-utils on the host.
  docker run --rm httpd:2-alpine htpasswd -Bbn "$RU" "$RP" > "$AUTH_DIR/htpasswd"
  chmod 644 "$AUTH_DIR/htpasswd"
  say "   wrote $AUTH_DIR/htpasswd for user $RU"
else
  say "   htpasswd already present - keeping it"
fi

say "6. the GitHub App key, if there is one"
# Same failure as the tunnel credential, different uid.
#
# The control plane runs as uid 999 inside its container and reads this key
# through a read-only mount. Downloaded from GitHub it lands root-owned at
# mode 600, so the app gets permission denied and reports "Could not reach
# GitHub to confirm the installation" -- which sends whoever reads it to check
# the key contents and the network, when the key is perfectly good and simply
# unreadable by the process that needs it.
GH_KEY="$REPO_DIR/deploy/github-app.pem"
if [ -s "$GH_KEY" ]; then
  chown 999:999 "$GH_KEY"
  chmod 600 "$GH_KEY"
  say "   $GH_KEY owned by uid 999"
else
  say "   none present - GitHub integration stays off until one is added"
fi

say "7. bringing the stack up"
# registry-tls serves the registry from this box instead of through the tunnel.
# Cloudflare's free plan rejects request bodies over 100MB, which every real
# image push exceeds, so a registry behind the tunnel builds fine and then
# fails at the push with a 413 that never reaches the registry at all.
# It needs fleetregistry.$ZONE to be a plain A record to this box with the
# proxy OFF - see step 8.
docker compose -f deploy/docker-compose.yml --profile tunnel --profile registry-tls up -d --build

say "8. what is running"
docker compose -f deploy/docker-compose.yml ps
cat <<EOF

  Check from anywhere:
      curl -s https://fleetapi.$ZONE/healthz

  A 530 means Cloudflare has no origin - the tunnel container is not connected.
  Read why with:
      docker logs fleet-tunnel --tail 40
EOF

say "9. one DNS record you must set by hand"
cat <<EOF
  Every hostname above is a proxied CNAME to the tunnel. fleetregistry.$ZONE
  must NOT be, because Cloudflare's free plan caps request bodies at 100MB and
  image layers routinely exceed that. Left proxied, builds succeed and pushes
  fail with "413 Payload Too Large" - from the edge, not from the registry.

  In the Cloudflare dashboard, DNS for $ZONE, set:

      Name     fleetregistry
      Type     A
      Content  $(curl -s --max-time 10 https://api.ipify.org || echo "<this box's public IP>")
      Proxy    DNS only (grey cloud)   <- the part that matters

  Caddy then gets a certificate over ACME automatically. Confirm with:
      curl -s -o /dev/null -w '%{http_code}\n' https://fleetregistry.$ZONE/v2/

  401 is the healthy answer: the registry is up and asking for credentials.
EOF
