#!/usr/bin/env bash
#
# Bring the whole stack up on a fresh control-plane box.
#
# Written to be run once, on a new Lightsail instance, from a browser terminal
# where scp is not available and every file has to be created in place.
#
# It generates its own secrets rather than asking for them. The alternative is
# carrying the previous box's keys forward by hand through a paste buffer,
# which is both worse for secrecy and a good way to typo a 64-character hex
# string into a container that will not say why it failed. The only things it
# cannot generate are the Cloudflare tunnel credential, which identifies this
# tunnel to Cloudflare, and the optional third-party keys.
#
# Idempotent: an existing .env is never overwritten, so re-running it after a
# failure does not silently rotate the database password out from under a
# volume that still holds data encrypted with the old one.
set -euo pipefail

REPO_DIR="${REPO_DIR:-/opt/fleet-os}"
ZONE="${ZONE:-plastikworld.xyz}"
TUNNEL_ID="${TUNNEL_ID:-12b87f0b-6409-4ecb-9946-53bc1bef50a7}"
CRED="/etc/fleet-os/tunnel-credentials.json"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
die() { printf '\n\033[31mFATAL: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run with sudo"

say "1. the tunnel credential"
if [ ! -s "$CRED" ]; then
  cat <<EOF
  Missing: $CRED

  On your Mac, print it:
      cat ~/.cloudflared/${TUNNEL_ID}.json*

  Then here:
      sudo mkdir -p /etc/fleet-os
      sudo tee $CRED >/dev/null <<'JSON'
      <paste the single line of JSON>
      JSON

  Re-run this script afterwards.
EOF
  exit 1
fi
python3 -c "import json,sys; json.load(open('$CRED'))" 2>/dev/null \
  || die "$CRED is not valid JSON - a paste probably wrapped or lost a character"
chmod 600 "$CRED"
# cloudflared runs as uid 65532 inside its container and reads this file
# through a read-only mount. Owned by root at mode 600 it gets permission
# denied and the tunnel never connects - which is exactly how the last
# migration lost three minutes of production.
chown 65532:65532 "$CRED"
say "   credential present and owned by uid 65532"

say "2. the repository"
if [ ! -d "$REPO_DIR/.git" ]; then
  mkdir -p "$(dirname "$REPO_DIR")"
  git clone --depth 50 https://github.com/YadurajManu/fleet-os.git "$REPO_DIR"
else
  git -C "$REPO_DIR" pull --ff-only
fi
cd "$REPO_DIR"
say "   at $(git -C "$REPO_DIR" rev-parse --short HEAD)"

say "3. secrets and .env"
ENV_FILE="$REPO_DIR/deploy/.env"
if [ -s "$ENV_FILE" ]; then
  say "   .env already exists - keeping it (delete it to regenerate)"
else
  gen() { openssl rand -hex 32; }
  # SECRETS_MASTER_KEY is the one that is NOT hex. The control plane decodes it
  # as base64 and checks it lands on exactly 32 bytes, so a 64-character hex
  # string decodes to 48 and is rejected - with a clear message, but only after
  # a full build, and only in a container log.
  genb64() { openssl rand -base64 32; }
  REG_PASS=$(openssl rand -hex 16)
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/aws/bring-up.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# The database is created fresh with these values. Rotating POSTGRES_PASSWORD
# later without also resetting the volume leaves a database nothing can open.
POSTGRES_USER=fleetos
POSTGRES_DB=fleetos
POSTGRES_PASSWORD=$(gen)

JWT_SECRET=$(gen)
# Encrypts secrets at rest. Lose it and every stored secret is unreadable -
# there is no recovery path, by design.
SECRETS_MASTER_KEY=$(genb64)
WEBHOOK_SECRET=$(gen)

REGISTRY_URL=fleetregistry.$ZONE
REGISTRY_CREDENTIALS=fleet:$REG_PASS
REGISTRY_PORT=5001

INGRESS_ZONE=$ZONE
INGRESS_PORT=8081
API_PORT=8080
DASHBOARD_PORT=8082
WWW_PORT=8083

APP_URL=https://fleetapp.$ZONE
PUBLIC_DASHBOARD_URL=https://fleetapp.$ZONE
PUBLIC_API_URL=https://fleetapi.$ZONE

HEARTBEAT_INTERVAL_SEC=5
HEARTBEAT_MISS_THRESHOLD=3
LOG_LEVEL=info
BUILDX_CACHE_MODE=min

TUNNEL_CREDENTIALS=$CRED

# Optional. Email falls back to logging what it would have sent, so an
# unconfigured control plane still runs normally - it just goes quiet.
RESEND_API_KEY=
MAIL_FROM=
EOF
  chmod 600 "$ENV_FILE"
  say "   wrote $ENV_FILE with fresh secrets"
fi

say "4. tunnel ingress"
CF="$REPO_DIR/deploy/cloudflare/fleet-os.yml"
if [ ! -s "$CF" ]; then
  sed -e "s/REPLACE_WITH_TUNNEL_ID/$TUNNEL_ID/g" -e "s/REPLACE_ZONE/$ZONE/g" \
      "$REPO_DIR/deploy/cloudflare/fleet-os.yml.example" > "$CF"
  say "   rendered $CF"
fi
# This path is gitignored, so Docker will happily create a DIRECTORY here if
# the file is absent, mount it, and leave cloudflared reading an empty config
# with no error that names the cause. Refuse to continue on anything but a file.
[ -f "$CF" ] || die "$CF is not a regular file - remove it and re-run"

say "5. bringing the stack up"
docker compose -f deploy/docker-compose.yml --profile tunnel up -d --build

say "6. what is running"
docker compose -f deploy/docker-compose.yml ps
cat <<EOF

  Check from anywhere:
      curl -s https://fleetapi.$ZONE/healthz

  A 530 means Cloudflare has no origin - the tunnel container is not connected.
  Read why with:
      docker logs fleet-tunnel --tail 40
EOF
