/**
 * The connection URL Fleet will inject for a managed database.
 *
 * `uses: [db]` gives a service DATABASE_URL and friends. An imported compose
 * file usually has its own variable for the same thing — MONGODB_URI,
 * DATABASE_URL, REDIS_URL — pointing at the compose service that just became a
 * managed database. Left alone that variable is either copied verbatim, so the
 * app dials a host that no longer exists, or moved to `secrets`, so the user is
 * asked to supply a value Fleet already knows. Both end in an app that deploys
 * and cannot reach its database.
 *
 * This is deliberately a copy of what the control plane computes, because the
 * CLI cannot import it — they are separate packages, and the CLI has to work
 * against a control plane it did not build. The copy is kept honest by a test
 * in the control plane that reads this file and fails when the two disagree,
 * which is the only thing that makes duplicating it acceptable.
 */

export type EngineWire = {
  scheme: string
  port: number
  defaultUser: string
  usesPassword: boolean
  usesDatabase: boolean
}

/** Mirrors ENGINES in control-plane/src/manifest/databases.ts. */
export const ENGINE_WIRE: Record<string, EngineWire> = {
  postgres: { scheme: 'postgres', port: 5432, defaultUser: 'postgres', usesPassword: true, usesDatabase: true },
  mysql: { scheme: 'mysql', port: 3306, defaultUser: 'app', usesPassword: true, usesDatabase: true },
  mariadb: { scheme: 'mysql', port: 3306, defaultUser: 'app', usesPassword: true, usesDatabase: true },
  redis: { scheme: 'redis', port: 6379, defaultUser: '', usesPassword: false, usesDatabase: false },
  mongo: { scheme: 'mongodb', port: 27017, defaultUser: 'app', usesPassword: true, usesDatabase: true },
}

/** Mirrors passwordRefFor: the secret name a database's password lives under. */
export const passwordRefFor = (name: string): string =>
  `${name.toUpperCase().replace(/[^A-Z0-9]+/g, '_')}_PASSWORD`

/**
 * The URL a service will see, written the way the manifest can carry it.
 *
 * The password is a `${secret:NAME}` reference rather than a value: it is
 * generated by the control plane and never known here, and a manifest is a
 * file people commit.
 */
export function injectedUrl(dbName: string, engine: string): string | null {
  const spec = ENGINE_WIRE[engine]
  if (!spec) return null
  const auth = spec.usesPassword
    ? `${encodeURIComponent(spec.defaultUser)}:\${secret:${passwordRefFor(dbName)}}@`
    : ''
  // `database` defaults to the declaration's own name, and the host is that
  // same name: containers resolve each other by service name on the node.
  const path = spec.usesDatabase ? `/${dbName}` : ''
  return `${spec.scheme}://${auth}${dbName}:${spec.port}${path}`
}

/** Does this value look like a connection URL aimed at `host`? */
export function pointsAt(value: string, host: string): boolean {
  // Scheme-relative on purpose: an app may hold a mongodb+srv:// or a
  // postgresql:// where Fleet writes postgres://, and the host is what says
  // this is the same database rather than an unrelated service.
  const match = value.match(/^[a-z][a-z0-9+.-]*:\/\/(?:[^@/]*@)?([^:/?#]+)/i)
  return match?.[1]?.toLowerCase() === host.toLowerCase()
}
